# Generated by Django 5.1.5 on 2025-02-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='concepts',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='difficulty',
            field=models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='examples',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='hints',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
