# Generated by Django 5.1.7 on 2025-04-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='content',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='model_used',
            field=models.CharField(default='gemini-pro', max_length=50),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='voice_message',
            field=models.BooleanField(default=False),
        ),
    ]
