# Generated by Django 5.1.5 on 2025-02-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0002_puzzle_concepts_puzzle_difficulty_puzzle_examples_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
