# Generated by Django 5.1.7 on 2025-04-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0002_rename_message_chatmessage_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='session_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
