# Generated by Django 5.1.5 on 2025-02-14 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle", "0003_userprogress_attempts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprogress",
            name="attempts",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="solved",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="solved_date",
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="puzzle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solutions",
                to="puzzle.puzzle",
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
