# Generated by Django 5.1.5 on 2025-02-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle", "0005_userprogress_attempts_userprogress_solved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="test_status",
            field=models.CharField(
                choices=[
                    ("pass", "Passed"),
                    ("fail", "Failed"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
