# Generated by Django 5.1.5 on 2025-02-15 20:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle", "0006_puzzle_test_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="puzzle",
            name="concepts",
        ),
        migrations.RemoveField(
            model_name="puzzle",
            name="explanation",
        ),
        migrations.AddField(
            model_name="puzzle",
            name="category",
            field=models.CharField(
                choices=[
                    ("basic", "Basic Python"),
                    ("oop", "Object-Oriented Programming"),
                    ("ds", "Data Structures"),
                    ("file", "File Handling"),
                ],
                default="basic",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="puzzle",
            name="test_results",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="test_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("pass", "Passed"),
                    ("fail", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="puzzle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="puzzle.puzzle"
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
