# Generated by Django 5.1.5 on 2025-02-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle", "0007_remove_puzzle_concepts_remove_puzzle_explanation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="concepts",
            field=models.CharField(
                blank=True,
                default="Variables, Functions, Control Flow",
                help_text="Comma-separated list of learning concepts",
                max_length=255,
            ),
        ),
    ]
