# Generated by Django 5.1.6 on 2025-02-16 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle", "0009_category_alter_userprogress_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["order"], "verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="category",
            name="icon_class",
            field=models.CharField(default="bi-journal-bookmark", max_length=50),
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.CharField(
                choices=[
                    ("basic", "Basic Python"),
                    ("oop", "Object-Oriented Programming"),
                    ("ds", "Data Structures"),
                    ("file", "File Handling"),
                ],
                max_length=10,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="category",
            field=models.ForeignKey(
                default="basic",
                on_delete=django.db.models.deletion.PROTECT,
                to="puzzle.category",
            ),
        ),
        migrations.CreateModel(
            name="StudyMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="puzzle.category",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
