# Generated by Django 5.1.6 on 2025-02-18 20:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle", "0010_alter_category_options_category_icon_class_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_code",
                    models.TextField(
                        help_text="User's submitted Python code",
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "submission_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp of submission"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("pass", "Approved"),
                            ("fail", "Needs Revision"),
                        ],
                        default="pending",
                        help_text="Review status",
                        max_length=10,
                    ),
                ),
                (
                    "admin_feedback",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="LLM analysis results in JSON format",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code Submission",
                "verbose_name_plural": "Code Submissions",
                "ordering": ["-submission_date"],
            },
        ),
        migrations.RemoveField(
            model_name="studymaterial",
            name="category",
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="category",
            field=models.CharField(
                default="Algorithm", help_text="Puzzle category/type", max_length=50
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userprogress",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="puzzle",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="puzzle",
            options={
                "ordering": ["-date"],
                "verbose_name": "Programming Puzzle",
                "verbose_name_plural": "Programming Puzzles",
            },
        ),
        migrations.RemoveField(
            model_name="puzzle",
            name="concepts",
        ),
        migrations.RemoveField(
            model_name="puzzle",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="puzzle",
            name="test_results",
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Publication date (one puzzle per day)",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="description",
            field=models.TextField(
                help_text="Detailed problem statement and requirements",
                validators=[django.core.validators.MinLengthValidator(50)],
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="examples",
            field=models.JSONField(
                default=list,
                help_text="JSON array of input/output examples [{'input': ..., 'output': ...}]",
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="hints",
            field=models.JSONField(
                default=list, help_text="JSON array of hints for solving the puzzle"
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="solution",
            field=models.TextField(
                help_text="Admin-only correct solution code",
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="test_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("pass", "Approved"),
                    ("fail", "Rejected"),
                ],
                default="pending",
                help_text="Approval status for publishing",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="title",
            field=models.CharField(
                help_text="Descriptive title for the puzzle",
                max_length=200,
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
        migrations.AddIndex(
            model_name="puzzle",
            index=models.Index(fields=["date"], name="puzzle_puzz_date_277857_idx"),
        ),
        migrations.AddIndex(
            model_name="puzzle",
            index=models.Index(
                fields=["test_status"], name="puzzle_puzz_test_st_1bdc77_idx"
            ),
        ),
        migrations.AddField(
            model_name="usersubmission",
            name="puzzle",
            field=models.ForeignKey(
                help_text="Associated puzzle",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_submissions",
                to="puzzle.puzzle",
            ),
        ),
        migrations.AddField(
            model_name="usersubmission",
            name="user",
            field=models.ForeignKey(
                help_text="User who submitted the solution",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="StudyMaterial",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="UserProgress",
        ),
        migrations.AddIndex(
            model_name="usersubmission",
            index=models.Index(
                fields=["submission_date"], name="puzzle_user_submiss_9ba64d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersubmission",
            index=models.Index(fields=["status"], name="puzzle_user_status_40d3bd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="usersubmission",
            unique_together={("user", "puzzle")},
        ),
    ]
