# Generated by Django 5.1.6 on 2025-02-19 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle", "0011_usersubmission_remove_studymaterial_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 20, 20, 42, 2, 692463, tzinfo=datetime.timezone.utc
                ),
                help_text="Submission deadline",
            ),
        ),
        migrations.AlterField(
            model_name="usersubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("pass", "Approved"),
                    ("fail", "Needs Revision"),
                ],
                default="pending",
                help_text="Review status",
                max_length=20,
            ),
        ),
    ]
